#! /bin/bash
picom -f &
nitrogen --restore &
/usr/bin/setxkbmap -option "caps:swapescape"
xrdb -merge /home/greg/.Xresources

dte(){
    dte="$(date +"  %a, %b %d | %l:%M%p")"
    echo -e "$dte"
}

mem(){
    mem=`free -h | awk '/Mem/ {print $3}'`
    echo -e "  $mem"
}

temps(){
    cpu=`sensors | awk '/Tctl/ {print $2}' | sed -r 's/[+°C]//g'`
    gpu=`sensors | awk '/junction/ {print $2}' | sed -r 's/[+°C]//g'`
    echo -e " $cpu / $gpu°C"
}

bat(){
    batsyms=(     )
    cap=`cat /sys/class/power_supply/BAT0/capacity`
    status=`cat /sys/class/power_supply/BAT0/status`
    index=`echo $cap | awk '{ print int($1/20) }'`

    [ "$status" = "Discharging" ] || sym=" " 
    echo -e "$sym${batsyms[$index]} $cap%"
    
}

vol(){
    vol=`amixer sget Master | awk -F"[][]" '/Front Left: Pla/ {print $2}'`
    echo -e "  $vol"
}

kernel(){
    kern=`uname -r | sed 's/-gentoo//g'`
    echo -e "  $kern"
}

internet(){

    [ -d /sys/class/net/tun* ] && vpn_sym=" [VPN]"
    [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = "up" ] && wifiicon=""
    [ "$(cat /sys/class/net/en*/operstate 2>/dev/null)" = "up" ] && ethicon=""

    echo -e "$ethicon$wifiicon$vpn_sym"
}

while true; do
    xsetroot -name " $(internet) | $(kernel) | $(vol) | $(temps) | $(mem) | $(bat) | $(dte)"
    sleep 1s
done &
