#! /bin/bash
picom -f &
nitrogen --restore &
/usr/bin/setxkbmap -option "caps:swapescape"
xrdb -merge /home/greg/.Xresources

dte(){
    dte="$(date +"  %a, %b %d | %l:%M%p")"
    echo -e "$dte"
}

mem(){
    mem=`free -h | awk '/Mem/ {print $3}'`
    echo -e "  $mem"
}

cpu(){
    cpu=`sensors | awk '/Tctl/ {print $2}' | head -n 1 | cut -c 2-3`
    gpu=`sensors | awk '/edge/ {print $2}' | head -n 1 | cut -c 2-3`
    echo -e " $cpu / $gpu°C"
}

bat(){
    batsyms=(     )
    cap=`cat /sys/class/power_supply/BAT0/capacity`
    status=`cat /sys/class/power_supply/BAT0/status`
    index=`awk '{ print int($1/20) }' /sys/class/power_supply/BAT0/capacity`

    [ "$status" = "Discharging" ] || sym=" " 
    echo -e "$sym${batsyms[$index]} $cap%"
    
}

vol(){
    vol=`amixer sget Master | awk -F"[][]" '/Front Left: Pla/ {print $2}'`
    echo -e "  $vol"
}

kernel(){
    kern=`uname -r | sed 's/-gentoo//g'`
    echo -e "  $kern"
}

internet(){
    [ -d /sys/class/net/tun* ] && vpn_sym=" [VPN]"

    case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
        down) wifiicon=""  ;;
	up)   wifiicon="" ;;
    esac
    case "$(cat /sys/class/net/en*/operstate 2>/dev/null)" in
        down) ethicon=""  ;;
	up)   ethicon="" ;;
    esac
    echo -e "$ethicon$wifiicon$vpn_sym"
}

while true; do
    xsetroot -name " $(internet) | $(kernel) | $(vol) | $(cpu) | $(mem) | $(bat) | $(dte)"
    sleep 1s
done &
