#!/bin/bash

curr_kernel=`uname -r | sed 's/-gentoo//'`

#Select Kernel
eselect kernel list
read -p 'Select your kernel: ' sel
eselect kernel set ${sel}

cp /etc/vanilla-kernel.conf /usr/src/linux/.config

#Build kernel
cd /usr/src/linux
make oldconfig
make -j$(nproc)
make modules_install
emerge @module-rebuild
make install

#Cleanup and create boot image
rm /boot/*${curr_kernel}*
rm -rf /usr/src/linux-${curr_kernel}*
grub-mkconfig -o /boot/grub/grub.cfg

#Replace config
cp /usr/src/linux/.config /etc/vanilla-kernel.conf
